version: 0.2

env:
  variables:
    TERRAFORM_VERSION: 1.1.3
    TF_DIRECTORY: src/terraform

phases:
  install:
    commands:
      - echo Starting install phase...
      - apt-get install -y wget
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  
  pre_build:
    commands:
      - echo "The TF_ACTION is $TF_ACTION"

  build:
    commands:
      - cd ${TF_DIRECTORY}
      - chmod +x terraform_script.sh
      - ./terraform_script.sh $TF_ACTION

